<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="https://evalanche//ewaf/view/xslt/wsdl-viewer.xsl"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="https://evalanche/soap.php/soap/mandator" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="EvalancheWebService">
    <types>
    </types>
    <portType name="WebServicePort">
    </portType>
    <binding name="WebServiceBinding" type="tns:WebServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    </binding>
    <service name="EvalancheWebService">
        <port name="WebServicePort" binding="tns:WebServiceBinding">
            <soap:address location="https://someservice"/>
        </port>
    </service>
</definitions>
